const pertEntry = [
    {
        codeNo: 1,
        code: "A",
        predecessor: [],
        description: "Sample Activity",
        a: 2,
        m: 3,
        b: 4,
    },
    {
        codeNo: 2,
        code: "B",
        predecessor: [],
        description: "Sample Activity",
        a: 3,
        m: 7,
        b: 7,
    },
    {
        codeNo: 3,
        code: "C",
        predecessor: ["A", "B"],
        description: "Sample Activity",
        a: 1,
        m: 2,
        b: 3,
    },
    {
        codeNo: 4,
        code: "D",
        predecessor: ["C"],
        description: "Sample Activity",
        a: 1,
        m: 3,
        b: 15,
    },
    {
        codeNo: 5,
        code: "E",
        predecessor: ["C"],
        description: "Sample Activity",
        a: 2,
        m: 3,
        b: 9,
    },
    {
        codeNo: 6,
        code: "F",
        predecessor: ["D"],
        description: "Sample Activity",
        a: 0,
        m: 4,
        b: 4,
    },
    {
        codeNo: 7,
        code: "G",
        predecessor: ["E"],
        description: "Sample Activity",
        a: 6,
        m: 8,
        b: 15,
    },
    {
        codeNo: 8,
        code: "H",
        predecessor: ["F"],
        description: "Sample Activity",
        a: 2,
        m: 2,
        b: 7,
    },
    {
        codeNo: 9,
        code: "I",
        predecessor: ["F"],
        description: "Sample Activity",
        a: 2,
        m: 2,
        b: 7,
    }
]