const pertEntry = [
    {
        codeNo: 1,
        code: "A",
        predecessor: [],
        description: "Planning",
        a: 1,
        m: 2,
        b: 3,
    },
    {
        codeNo: 2,
        code: "B",
        predecessor: ["A"],
        description: "Concept Paper",
        a: 2,
        m: 4,
        b: 5,
    },
    {
        codeNo: 3,
        code: "C",
        predecessor: ["B"],
        description: "D3.js Tutorial",
        a: 1,
        m: 2,
        b: 3,
    },
    {
        codeNo: 4,
        code: "D",
        predecessor: ["B"],
        description: "Coding (PERT Table)",
        a: 3,
        m: 4,
        b: 5,
    },
    {
        codeNo: 5,
        code: "E",
        predecessor: ["C", "D"],
        description: "Coding (Network Graph)",
        a: 3,
        m: 4,
        b: 5,
    },
    {
        codeNo: 6,
        code: "F",
        predecessor: ["E"],
        description: "Coding (Gantt Chart)",
        a: 2,
        m: 3,
        b: 5,
    },
    {
        codeNo: 7,
        code: "G",
        predecessor: ["D"],
        description: "UI/UX Designing",
        a: 2,
        m: 3,
        b: 4,
    },
    {
        codeNo: 8,
        code: "H",
        predecessor: ["F"],
        description: "Code Finalization",
        a: 1,
        m: 2,
        b: 3,
    },
    {
        codeNo: 9,
        code: "I",
        predecessor: ["F"],
        description: "Documentation and Presentation Preparation",
        a: 2,
        m: 3,
        b: 4,
    }
]